'use strict';
Chart.defaults.font.family='system-ui,-apple-system,sans-serif';Chart.defaults.elements.bar.borderRadius=6;
const $=s=>document.querySelector(s),app=$('#app'),dlg=$('#dlg');
const fmt=n=>new Intl.NumberFormat('vi-VN').format(Math.round(n))+' ₫';
const pc=n=>(isFinite(n)?n.toFixed(1).replace('.',','):'0')+'%';
const chg=(a,b)=>b?((a-b)/Math.abs(b)*100):(a?100:0);
const sg=n=>(n>0?'+':'')+pc(n);
const p2=n=>String(n).padStart(2,'0'),td=()=>{const d=new Date();return d.getFullYear()+'-'+p2(d.getMonth()+1)+'-'+p2(d.getDate())};
const dmy=s=>s.split('-').reverse().join('/');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const IC={food:['Ăn uống','M7 3v8M5 3v5a2 2 0 0 0 4 0V3M7 11v10M17 21V3c-2 1-3 4-3 8h3'],cart:['Đi chợ','M3 4h3l2 12h10l2-8H7M9 20h.01M17 20h.01'],house:['Nhà ở','M4 21V9l8-6 8 6v12M9 21v-7h6v7'],car:['Xe cộ','M5 17h14M4 17v-4l2-5h12l2 5v4M7 17v2M17 17v2M7 13h.01M17 13h.01'],bag:['Mua sắm','M5 8h14l-1 12H6zM9 8V6a3 3 0 0 1 6 0v2'],bulb:['Hóa đơn','M9 18h6M10 21h4M12 3a6 6 0 0 0-4 10c1 1 1 2 1 3h6c0-1 0-2 1-3a6 6 0 0 0-4-10z'],game:['Giải trí','M6 8h12a3 3 0 0 1 3 3v3a3 3 0 0 1-5 2l-1-1H9l-1 1a3 3 0 0 1-5-2v-3a3 3 0 0 1 3-3zM8 10v4M6 12h4M16 11h.01M18 13h.01'],heart:['Sức khỏe','M12 20s-8-5-8-11a4.5 4.5 0 0 1 8-2 4.5 4.5 0 0 1 8 2c0 6-8 11-8 11z'],book:['Sách vở','M4 5h6a2 2 0 0 1 2 2v13a2 2 0 0 0-2-2H4zM20 5h-6a2 2 0 0 0-2 2v13a2 2 0 0 1 2-2h6z'],plane:['Du lịch','M21 3L3 10l7 3 3 7zM10 13l11-10'],shirt:['Quần áo','M8 3l-5 4 3 3 2-1v12h8V9l2 1 3-3-5-4a4 4 0 0 1-8 0z'],gift:['Quà tặng','M4 10h16v10H4zM3 7h18v3H3zM12 7v13M12 7c-2 0-4-1-4-3s3-2 4 3c1-5 4-5 4-3s-2 3-4 3'],box:['Khác','M3 7l9-4 9 4v10l-9 4-9-4zM3 7l9 4 9-4M12 11v10'],briefcase:['Công việc','M3 8h18v12H3zM9 8V5h6v3M3 13h18'],star:['Ngôi sao','M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z'],laptop:['Máy tính','M5 5h14v10H5zM2 19h20'],trend:['Tăng trưởng','M3 17l6-6 4 4 8-8M15 7h6v6'],dash:['','M4 4h7v9H4zM13 4h7v5h-7zM13 11h7v9h-7zM4 15h7v5H4z'],list:['','M4 6h16M4 12h16M4 18h10'],chart:['','M4 20v-8M10 20V5M16 20v-11M2 20h20'],cal:['','M4 6h16v14H4zM4 10h16M8 3v4M16 3v4'],gear:['','M4 7h10M18 7h2M4 17h2M10 17h10M16 4v6M8 14v6'],plus:['','M12 5v14M5 12h14'],edit:['','M4 20h4L19 9l-4-4L4 16zM13 7l4 4'],trash:['','M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13'],m5:['','M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM9 10h.01M15 10h.01M8 14c1 2.5 2.5 3.5 4 3.5s3-1 4-3.5'],m4:['','M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM9 10h.01M15 10h.01M9 15c.8.8 1.8 1.2 3 1.2s2.2-.4 3-1.2'],m3:['','M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM9 10h.01M15 10h.01M9 15.5h6'],m2:['','M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM9 10h.01M15 10h.01M9 16c.8-.8 1.8-1.2 3-1.2s2.2.4 3 1.2'],m1:['','M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM9 10h.01M15 10h.01M8 17c1-2.5 2.5-3.5 4-3.5s3 1 4 3.5'],prev:['','M15 5l-7 7 7 7'],next:['','M9 5l7 7-7 7']};
const CI=['food','cart','house','car','bag','bulb','game','heart','book','plane','shirt','gift','box','briefcase','star','laptop','trend'];
const EM={'🍜':'food','🏠':'house','🚗':'car','🛒':'bag','💡':'bulb','🎮':'game','❤️':'heart','📚':'book','✈️':'plane','👕':'shirt','🎁':'gift','📦':'box','💼':'briefcase','💰':'star','🧑‍💻':'laptop','📈':'trend'};
const ico=(k,n=20)=>{k=EM[k]||k;return IC[k]?`<svg viewBox="0 0 24 24" width="${n}" height="${n}" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" style="vertical-align:-4px;flex:none"><path d="${IC[k][1]}"/></svg>`:`<span style="font-size:${n}px;line-height:1">${esc(k)}</span>`};
const iconOpts=c=>{c=EM[c]||c;return[...CI,...(CI.includes(c)?[]:[c])].map(k=>`<option value="${esc(k)}" ${k==c?'selected':''}>${IC[k]?IC[k][0]:esc(k)}</option>`).join('')};
const INK=()=>getComputedStyle(document.documentElement).getPropertyValue('--ink').trim(),nf=n=>new Intl.NumberFormat('vi-VN').format(n);
const fc=n=>{const a=Math.abs(n),g=n<0?'-':'',t=(v,u)=>g+v.toFixed(2).replace(/\.?0+$/,'').replace('.',',')+u;return a>=1e9?t(a/1e9,' tỷ'):a>=1e6?t(a/1e6,'tr'):a>=1e3?g+Math.round(a/1e3)+'k':g+Math.round(a)};
const dv=a=>a?(a%1000?nf(a):nf(a/1000)+'.000'):'';
const val=el=>{let v=el.value;if(el.dataset.ex)return+v.replace(/\D/g,'');if(v.endsWith('.000'))v=v.slice(0,-4);return(+v.replace(/\D/g,''))*1000};
const cl=e=>{const el=e.target;if(!el.dataset.ex&&el.value.endsWith('.000')){const m=el.value.length-4;setTimeout(()=>{if(el.selectionStart>m)el.setSelectionRange(m,m)})}};
const daily=m=>{const a=Array(new Date(+m.slice(0,4),+m.slice(5),0).getDate()).fill(0);inM(m).forEach(t=>{if(t.type=='expense')a[+t.date.slice(8)-1]+=t.amount});return a};
const dayInfo=k=>{const l=T.filter(t=>t.date==k&&t.type=='expense');return{c:byCat(l),top:[...l].sort((a,b)=>b.amount-a.amount)[0]}};
const topLine=k=>{const d=dayInfo(k),q=cat(d.c[0][0]);return`<p style="margin:0 0 8px;color:var(--mut)">Chi nhiều nhất: <b style="color:var(--ink)">${esc(q.name)}</b> (${fmt(d.c[0][1])})</p>`};
const dcard=m=>{const a=daily(m),bd=S.daily,tot=a.reduce((x,y)=>x+y,0),used=a.filter(v=>v>0).length,over=bd?a.filter(v=>v>bd).length:0;
if(!tot)return'<div class="card"><h3 style="margin-top:0">Chi tiêu từng ngày</h3><p class="empty">Chưa có chi tiêu trong tháng này.</p></div>';
return`<div class="card"><h3 style="margin-top:0">Chi tiêu từng ngày</h3><p style="color:var(--mut);font-size:13px;margin:0 0 8px">Trung bình ${fmt(tot/used)}/ngày có chi · ${over} ngày vượt chỉ tiêu (${fmt(bd)}/ngày)</p><div class="cv"><canvas id="c3"></canvas></div><p style="color:var(--mut);font-size:13px;margin:12px 0 4px">Bấm vào từng ngày để xem chi tiết các khoản chi.</p>${a.map((v,i)=>{if(!v)return'';const k=m+'-'+p2(i+1),d=dayInfo(k),tc=cat(d.c[0][0]);return`<details class="dd"><summary><span>${p2(i+1)}/${m.slice(5)}</span><span class="tc">${ico(tc.icon,16)} ${esc(tc.name)}</span><b>${fmt(v)}</b><i style="color:var(--${v>bd?'bad':'ok'})">${bd?(v>bd?'+':'-')+fc(Math.abs(v-bd)):''}</i></summary>${d.c.map(([id,x])=>{const q=cat(id);return`<div style="margin:8px 0"><div style="display:flex;justify-content:space-between;gap:8px"><span>${ico(q.icon,16)} ${esc(q.name)}</span><span>${fmt(x)} · ${pc(x/v*100)}</span></div><div class="bar"><i style="width:${x/v*100}%;background:${q.color}"></i></div></div>`}).join('')}<small style="color:var(--mut)">Khoản lớn nhất: ${esc(cat(d.top.categoryId).name)}${d.top.note?' – '+esc(d.top.note):''} (${fmt(d.top.amount)})</small></details>`}).join('')}</div>`};
const dchart=m=>{const a=daily(m),bd=S.daily,bad=getComputedStyle(document.documentElement).getPropertyValue('--bad').trim();mk('c3',{type:'bar',data:{labels:a.map((_,i)=>i+1),datasets:[{label:'Chi tiêu',data:a,backgroundColor:a.map(v=>bd&&v>bd?bad:INK())},...(bd?[{type:'line',label:'Chỉ tiêu',data:a.map(()=>bd),borderColor:'#8a8a8a',borderDash:[5,4],pointRadius:0,borderWidth:1.5}]:[])]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:tick(),maxTicksLimit:16}},y:{ticks:{color:tick(),callback:v=>fc(v)}}}}})};
const addD=(k,n)=>{const d=new Date(+k.slice(0,4),+k.slice(5,7)-1,+k.slice(8)+n);return d.getFullYear()+'-'+p2(d.getMonth()+1)+'-'+p2(d.getDate())};
const monday=k=>addD(k,-((new Date(+k.slice(0,4),+k.slice(5,7)-1,+k.slice(8)).getDay()+6)%7));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const shift=(m,d)=>{let[y,mo]=m.split('-').map(Number);mo+=d;while(mo<1){mo+=12;y--}while(mo>12){mo-=12;y++}return y+'-'+p2(mo)};
/* ---- IndexedDB ---- */
let db;
const openDB=()=>new Promise((ok,no)=>{const r=indexedDB.open('moneyflow',2);r.onupgradeneeded=()=>{const d=r.result,n=d.objectStoreNames;['transactions','categories','journal'].forEach(k=>n.contains(k)||d.createObjectStore(k,{keyPath:'id'}));n.contains('settings')||d.createObjectStore('settings',{keyPath:'key'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const run=(s,f)=>new Promise((ok,no)=>{const t=db.transaction(s,'readwrite'),st=[].concat(s).map(n=>t.objectStore(n)),q=f(...st);t.oncomplete=()=>ok(q&&q.result);t.onerror=()=>no(t.error)});
const getAll=s=>new Promise((ok,no)=>{const q=db.transaction(s).objectStore(s).getAll();q.onsuccess=()=>ok(s=='categories'?q.result.sort((a,b)=>rk(a)-rk(b)):q.result);q.onerror=()=>no(q.error)});
const PAL={c0:'#F97316',c17:'#22A06B',c1:'#6366F1',c2:'#0EA5E9',c3:'#EC4899',c4:'#EAB308',c5:'#8B5CF6',c6:'#EF4444',c7:'#14B8A6',c8:'#06B6D4',c9:'#D946EF',c10:'#F43F5E',c11:'#64748B',c12:'#16A34A',c13:'#84CC16',c14:'#10B981',c15:'#0D9488',c16:'#64748B'};
const DC=[['c0','e','food','Ăn uống'],['c17','e','cart','Đi chợ'],['c1','e','house','Nhà ở'],['c2','e','car','Di chuyển'],['c3','e','bag','Mua sắm'],['c4','e','bulb','Hóa đơn'],['c5','e','game','Giải trí'],['c6','e','heart','Sức khỏe'],['c7','e','book','Giáo dục'],['c8','e','plane','Du lịch'],['c9','e','shirt','Thời trang'],['c10','e','gift','Quà tặng'],['c11','e','box','Khác'],['c12','i','briefcase','Lương'],['c13','i','star','Thưởng'],['c14','i','laptop','Freelance'],['c15','i','trend','Đầu tư'],['c16','i','gift','Khác']].map((c,i)=>({id:c[0],type:c[1]=='e'?'expense':'income',icon:c[2],name:c[3],color:PAL[c[0]]}));
const rk=c=>{const i=DC.findIndex(d=>d.id==c.id);return i<0?99:i};
let T=[],C=[],S={theme:'system',daily:300000},V='dash',M=td().slice(0,7),Y=+td().slice(0,4),RT='m',F={},CALD=null,charts=[],WK=monday(td()),J=[],JD=td(),JQ='',CT='c';const MOODS=['Rất tốt','Tốt','Bình thường','Mệt','Tệ'],MI={'Rất tốt':'m5','Tốt':'m4','Bình thường':'m3','Mệt':'m2','Tệ':'m1'};let jFlush=null;
const cat=id=>C.find(c=>c.id==id)||{icon:'box',name:'Đã xóa',color:'#888'};
const sum=(l,t)=>l.filter(x=>x.type==t).reduce((a,x)=>a+x.amount,0);
const stat=l=>{const i=sum(l,'income'),e=sum(l,'expense');return{i,e,r:i-e,s:i?(i-e)/i*100:0}};
const inM=m=>T.filter(t=>t.date.startsWith(m)),inY=y=>T.filter(t=>t.date.startsWith(y+'-'));
const byCat=l=>{const o={};l.filter(t=>t.type=='expense').forEach(t=>o[t.categoryId]=(o[t.categoryId]||0)+t.amount);return Object.entries(o).sort((a,b)=>b[1]-a[1])};
/* ---- theme ---- */
const applyTheme=()=>{const d=S.theme=='dark'||(S.theme=='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=d?'dark':'light'};
matchMedia('(prefers-color-scheme:dark)').addEventListener('change',applyTheme);
const saveS=()=>run('settings',s=>s.put({key:'theme',value:S.theme}));
/* ---- ui helpers ---- */
const kpis=s=>`<div class="hero"><small>Còn lại</small><b>${fmt(s.r)}</b><span class="pill">Tiết kiệm ${pc(s.s)}</span></div><div class="kpis"><div class="kpi"><small>Thu nhập</small><b class="inc">${fmt(s.i)}</b></div><div class="kpi"><small>Chi tiêu</small><b class="exp">${fmt(s.e)}</b></div></div>`;
const txRow=t=>{const c=cat(t.categoryId);return`<div class="row"><div class="ic" style="background:${c.color}22;color:${c.color}">${ico(c.icon,18)}</div><div class="m"><b>${esc(c.name)}</b><small>${dmy(t.date)}${t.note?' · '+esc(t.note):''}</small>${t.items&&t.items.length?'<div class="its">'+t.items.map(x=>`<span>${esc(x.name||'—')}</span><span>${fmt(x.amount||0)}</span>`).join('')+'</div>':''}</div><div class="a ${t.type=='income'?'inc':'exp'}">${t.type=='income'?'+':'-'}${fmt(t.amount)}</div><button data-e="${t.id}" aria-label="Sửa">${ico('edit',18)}</button><button data-d="${t.id}" aria-label="Xóa">${ico('trash',18)}</button></div>`};
const empty=()=>`<div class="card empty"><b>Chưa có giao dịch</b><p>Hãy thêm giao dịch đầu tiên để bắt đầu theo dõi chi tiêu.</p><button data-add>+ Thêm giao dịch</button></div>`;
const pn=l=>`<div class="pn"><button data-p="-1">←</button><b>${l}</b><button data-p="1">→</button></div>`;
const mLabel=m=>'Tháng '+m.slice(5)+'/'+m.slice(0,4);
const catBars=l=>{const c=byCat(l),tot=c.reduce((a,x)=>a+x[1],0);return c.length?c.map(([id,v])=>{const k=cat(id);return`<div style="margin:10px 0;cursor:pointer" data-cat="${id}"><div style="display:flex;justify-content:space-between"><span>${ico(k.icon,16)} ${esc(k.name)}</span><span>${fmt(v)} · ${pc(v/tot*100)}</span></div><div class="bar"><i style="width:${v/tot*100}%;background:${k.color}"></i></div></div>`}).join(''):'<p class="empty">Không có chi tiêu.</p>'};
const mk=(id,cfg)=>{const e=document.getElementById(id);if(e)charts.push(new Chart(e,{...cfg,options:{responsive:true,maintainAspectRatio:false,...cfg.options}}))};
const donut=(id,l)=>{const c=byCat(l);mk(id,{type:'doughnut',data:{labels:c.map(x=>cat(x[0]).name),datasets:[{data:c.map(x=>x[1]),backgroundColor:c.map(x=>cat(x[0]).color),borderWidth:0}]},options:{plugins:{legend:{position:innerWidth<600?'bottom':'right',labels:{color:getComputedStyle(document.body).color,boxWidth:12}}}}})};
const tick=()=>getComputedStyle(document.body).color;
const cmpChart=(id,a,b,la,lb)=>mk(id,{type:'bar',data:{labels:['Thu nhập','Chi tiêu','Còn lại'],datasets:[{label:la,data:[a.i,a.e,a.r],backgroundColor:'#b5b5b5'},{label:lb,data:[b.i,b.e,b.r],backgroundColor:INK()}]},options:{plugins:{legend:{labels:{color:tick()}}},scales:{x:{ticks:{color:tick()}},y:{ticks:{color:tick(),callback:v=>fc(v)}}}}});
/* ---- views ---- */
function dash(){const l=inM(M),s=stat(l);
app.innerHTML=`<h2>Tổng quan — ${mLabel(M)}</h2>${pn(mLabel(M))}${T.length?kpis(s)+`<div class="card" style="margin-top:14px"><h3 style="margin-top:0">Biểu đồ thu / chi</h3><div class="cv"><canvas id="c1"></canvas></div></div><div class="card"><h3 style="margin-top:0">Chi tiêu theo danh mục</h3>${l.some(t=>t.type=='expense')?'<div class="cv"><canvas id="c2"></canvas></div>':'<p class="empty">Chưa có chi tiêu trong tháng này.</p>'}</div><div class="card"><h3 style="margin-top:0">Giao dịch gần đây</h3>${[...T].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).slice(0,5).map(txRow).join('')}</div>`:empty()}`;
if(T.length){mk('c1',{type:'bar',data:{labels:['Thu nhập','Chi tiêu','Còn lại'],datasets:[{data:[s.i,s.e,s.r],backgroundColor:[INK(),'#8a8a8a','#c4c4c4']}]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:tick()}},y:{ticks:{color:tick(),callback:v=>fc(v)}}}}});if(l.some(t=>t.type=='expense'))donut('c2',l)}}
function txs(){const f=F;let l=T.filter(t=>(!f.q||(t.note+cat(t.categoryId).name).toLowerCase().includes(f.q.toLowerCase()))&&(!f.m||t.date.startsWith(f.m))&&(!f.d1||t.date>=f.d1)&&(!f.d2||t.date<=f.d2)&&(!f.y||t.date.startsWith(f.y+'-'))&&(!f.t||t.type==f.t)&&(!f.c||t.categoryId==f.c)&&(!f.a||t.amount>=f.a)&&(!f.b||t.amount<=f.b));
l.sort((a,b)=>(f.o=='asc'?1:-1)*(a.date.localeCompare(b.date)||a.createdAt-b.createdAt));
let h='',last='';l.forEach(t=>{if(t.date!=last){h+=`<h3>${dmy(t.date)}</h3>`;last=t.date}h+=txRow(t)});
const ys=[...new Set(T.map(t=>t.date.slice(0,4)))].sort();
app.innerHTML=`<h2>Giao dịch</h2><div class="tools"><input id="fq" placeholder="Tìm kiếm" value="${esc(f.q||'')}"><input id="fm" type="month" value="${f.m||''}"><select id="fy"><option value="">Mọi năm</option>${ys.map(y=>`<option ${f.y==y?'selected':''}>${y}</option>`).join('')}</select><select id="ft"><option value="">Thu & chi</option><option value="income" ${f.t=='income'?'selected':''}>Thu nhập</option><option value="expense" ${f.t=='expense'?'selected':''}>Chi tiêu</option></select><select id="fc"><option value="">Mọi danh mục</option>${C.map(c=>`<option value="${c.id}" ${f.c==c.id?'selected':''}>${esc(c.name)} (${c.type=='income'?'thu':'chi'})</option>`).join('')}</select><input id="fa" type="number" min="0" placeholder="Từ số tiền" value="${f.a||''}"><input id="fb" type="number" min="0" placeholder="Đến số tiền" value="${f.b||''}"><select id="fo"><option value="desc">Mới nhất</option><option value="asc" ${f.o=='asc'?'selected':''}>Cũ nhất</option></select><button data-clr>Xóa lọc</button></div><div class="card">${l.length?h:T.length?'<p class="empty">Không có giao dịch phù hợp.</p>':empty()}</div>`;
const g=(id,k,n)=>{$('#'+id).onchange=e=>{f[k]=n?+e.target.value||0:e.target.value;txs()}};g('fm','m');g('fy','y');g('ft','t');g('fc','c');g('fa','a',1);g('fb','b',1);g('fo','o');
$('#fq').oninput=e=>{f.q=e.target.value;const p=e.target.selectionStart;txs();const q=$('#fq');q.focus();q.setSelectionRange(p,p)}}
const ddRow=(k,v,bd)=>{const d=dayInfo(k),tc=cat(d.c[0][0]);return`<details class="dd"><summary><span>${dmy(k).slice(0,5)}</span><span class="tc">${ico(tc.icon,16)} ${esc(tc.name)}</span><b>${fmt(v)}</b><i style="color:var(--${v>bd?'bad':'ok'})">${bd?(v>bd?'+':'-')+fc(Math.abs(v-bd)):''}</i></summary>${d.c.map(([id,x])=>{const q=cat(id);return`<div style="margin:8px 0"><div style="display:flex;justify-content:space-between;gap:8px"><span>${ico(q.icon,16)} ${esc(q.name)}</span><span>${fmt(x)} · ${pc(x/v*100)}</span></div><div class="bar"><i style="width:${x/v*100}%;background:${q.color}"></i></div></div>`}).join('')}<small style="color:var(--mut)">Khoản lớn nhất: ${esc(cat(d.top.categoryId).name)}${d.top.note?' – '+esc(d.top.note):''} (${fmt(d.top.amount)})</small></details>`};
const dbars=(id,a,lb)=>{const bd=S.daily,bad=getComputedStyle(document.documentElement).getPropertyValue('--bad').trim();mk(id,{type:'bar',data:{labels:lb,datasets:[{label:'Chi tiêu',data:a,backgroundColor:a.map(v=>bd&&v>bd?bad:INK())},...(bd?[{type:'line',label:'Chỉ tiêu',data:a.map(()=>bd),borderColor:'#8a8a8a',borderDash:[5,4],pointRadius:0,borderWidth:1.5}]:[])]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:tick()}},y:{ticks:{color:tick(),callback:v=>fc(v)}}}}})};
function wk(tabs){const ks=[...Array(7)].map((_,i)=>addD(WK,i)),l=T.filter(t=>t.date>=ks[0]&&t.date<=ks[6]),s=stat(l),pk=addD(WK,-7),ps=stat(T.filter(t=>t.date>=pk&&t.date<WK)),bd=S.daily,a=ks.map(k=>l.filter(t=>t.date==k&&t.type=='expense').reduce((x,t)=>x+t.amount,0)),days=ks.map((k,i)=>a[i]?ddRow(k,a[i],bd):'').join('');
app.innerHTML=`<h2>Báo cáo</h2>${tabs}${pn(dmy(ks[0]).slice(0,5)+' – '+dmy(ks[6]))}${kpis(s)}<div class="card" style="margin-top:14px"><h3 style="margin-top:0">Chi tiêu từng ngày trong tuần</h3><div class="cv"><canvas id="c1"></canvas></div></div><div class="card"><h3 style="margin-top:0">Chi tiêu theo danh mục</h3>${catBars(l)}</div><div class="card"><h3 style="margin-top:0">So sánh với tuần trước</h3><table><tr><th></th><th>Tuần trước</th><th>Tuần này</th><th>Đổi</th></tr>${[['Thu nhập','i'],['Chi tiêu','e'],['Còn lại','r']].map(([n,k])=>`<tr><td>${n}</td><td>${fc(ps[k])}</td><td>${fc(s[k])}</td><td>${sg(chg(s[k],ps[k]))}</td></tr>`).join('')}</table></div><div class="card"><h3 style="margin-top:0">Chi tiết từng ngày</h3>${days?'<p style="color:var(--mut);font-size:13px;margin:0 0 4px">Bấm vào từng ngày để xem chi tiết các khoản chi.</p>'+days:'<p class="empty">Chưa có chi tiêu trong tuần này.</p>'}</div>`;
dbars('c1',a,['T2','T3','T4','T5','T6','T7','CN'])}
function rep(){const tabs=`<div class="seg"><button data-rt="w" class="${RT=='w'?'on':''}">Tuần</button><button data-rt="m" class="${RT=='m'?'on':''}">Tháng</button><button data-rt="y" class="${RT=='y'?'on':''}">Năm</button></div>`;
if(RT=='w'){wk(tabs);return}
if(RT=='m'){const s=stat(inM(M)),pm=shift(M,-1),ps=stat(inM(pm));
app.innerHTML=`<h2>Báo cáo</h2>${tabs}${pn(mLabel(M))}${kpis(s)}<div class="card" style="margin-top:14px"><h3 style="margin-top:0">Chi tiêu theo danh mục</h3>${s.e?'<div class="cv"><canvas id="c1"></canvas></div>':''}${catBars(inM(M))}</div>${dcard(M)}<div class="card"><h3 style="margin-top:0">So sánh ${mLabel(pm)} với ${mLabel(M)}</h3><table><tr><th></th><th>T${pm.slice(5)}</th><th>T${M.slice(5)}</th><th>Đổi</th></tr>${[['Thu nhập','i'],['Chi tiêu','e'],['Còn lại','r']].map(([n,k])=>`<tr><td>${n}</td><td>${fc(ps[k])}</td><td>${fc(s[k])}</td><td>${sg(chg(s[k],ps[k]))}</td></tr>`).join('')}<tr><td>Tỷ lệ tiết kiệm</td><td>${pc(ps.s)}</td><td>${pc(s.s)}</td><td>${sg(chg(s.s,ps.s))}</td></tr></table><div class="cv" style="margin-top:12px"><canvas id="c2"></canvas></div></div>`;
if(s.e)donut('c1',inM(M));cmpChart('c2',ps,s,'T'+pm.slice(5),'T'+M.slice(5));dchart(M)}
else{const l=inY(Y),s=stat(l),ps=stat(inY(Y-1));
app.innerHTML=`<h2>Báo cáo</h2>${tabs}${pn('Năm '+Y)}<h3 style="margin-top:0">BÁO CÁO TÀI CHÍNH ${Y}</h3>${kpis(s)}<div class="card" style="margin-top:14px"><h3 style="margin-top:0">Thu nhập / chi tiêu ${Y}</h3><div class="chk"><label><input type="checkbox" data-sr="0" checked> Income</label><label><input type="checkbox" data-sr="1" checked> Expense</label><label><input type="checkbox" data-sr="2" checked> Remaining</label></div><div class="cv"><canvas id="c1"></canvas></div></div><div class="card"><h3 style="margin-top:0">Chi tiêu năm ${Y}</h3>${catBars(l)}</div><div class="card"><h3 style="margin-top:0">So sánh ${Y-1} với ${Y}</h3><table><tr><th></th><th>${Y-1}</th><th>${Y}</th><th>Đổi</th></tr>${[['Thu nhập','i'],['Chi tiêu','e'],['Còn lại','r']].map(([n,k])=>`<tr><td>${n}</td><td>${fc(ps[k])}</td><td>${fc(s[k])}</td><td>${sg(chg(s[k],ps[k]))}</td></tr>`).join('')}</table></div>`;
const ms=[...Array(12)].map((_,i)=>stat(inM(Y+'-'+p2(i+1))));
mk('c1',{type:'bar',data:{labels:ms.map((_,i)=>'T'+(i+1)),datasets:[{label:'Thu nhập',data:ms.map(m=>m.i),backgroundColor:INK()},{label:'Chi tiêu',data:ms.map(m=>m.e),backgroundColor:'#8a8a8a'},{label:'Còn lại',data:ms.map(m=>m.r),backgroundColor:'#c4c4c4'}]},options:{plugins:{legend:{display:false}},scales:{x:{ticks:{color:tick()}},y:{ticks:{color:tick(),callback:v=>fc(v)}}}}});
document.querySelectorAll('[data-sr]').forEach(e=>e.onchange=()=>{const c=charts[0];c.setDatasetVisibility(+e.dataset.sr,e.checked);c.update()})}}
const ctabs=()=>`<div class="seg"><button data-ct="c" class="${CT=='c'?'on':''}">Lịch</button><button data-ct="j" class="${CT=='j'?'on':''}">Nhật ký</button></div>`;
const jBlock=k=>{const e=J.find(x=>x.id==k);return`<div style="margin-top:12px;border-top:1px solid var(--line);padding-top:10px"><b>Nhật ký</b>${e?`<div style="white-space:pre-wrap;overflow-wrap:anywhere;color:var(--mut);margin:4px 0">${esc(e.text.length>200?e.text.slice(0,200)+'…':e.text)}</div>`:''}<div class="btns"><button data-jw>${e?'Sửa nhật ký':'Viết nhật ký'}</button></div></div>`};
const wd=k=>['Chủ nhật','Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy'][new Date(+k.slice(0,4),+k.slice(5,7)-1,+k.slice(8)).getDay()];
const jlist=()=>{const q=JQ.toLowerCase(),L=J.filter(x=>!q||(x.text+(x.mood||'')).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));if(!L.length)return'<p class="empty">'+(JQ?'Không tìm thấy.':'Chưa có nhật ký nào.')+'</p>';let h='',last='';
L.forEach(x=>{const mo=x.date.slice(0,7);if(mo!=last){h+=`<h3>${mLabel(mo)}</h3>`;last=mo}const sp=T.filter(t=>t.date==x.date&&t.type=='expense').reduce((a,t)=>a+t.amount,0);
h+=`<div class="jc ${x.id==JD?'cur':''}" data-jd="${x.date}"><div class="jd"><b>${x.date.slice(8)}</b><small>${wd(x.date).replace('Thứ ','T').replace('Chủ nhật','CN')}</small></div><div class="jb"><div class="jh">${x.mood?ico(MI[x.mood]||'m3',16)+'<span>'+esc(x.mood)+'</span>':''}${sp?'<span class="jsp">Chi '+fc(sp)+'</span>':''}</div><div class="jt">${esc(x.text)}</div></div><button data-jx="${x.id}" aria-label="Xóa">${ico('trash',18)}</button></div>`});return h};
function jr(){const day=JD,e=J.find(x=>x.id==day),to=day==td(),sp=T.filter(t=>t.date==day&&t.type=='expense').reduce((a,t)=>a+t.amount,0);let txt=e?e.text:'',mood=e&&e.mood||'',dirty=false,timer;
app.classList.add('wide');
app.innerHTML=`<h2>Lịch</h2>${ctabs()}<div class="jgrid"><div class="jed card"><div class="jtop"><button data-jn="-1" aria-label="Hôm trước">${ico('prev',20)}</button><label class="jdate"><b>${wd(day)}</b><span>${dmy(day)}</span><input id="jdi" type="date" value="${day}"></label><button data-jn="1" aria-label="Hôm sau">${ico('next',20)}</button></div><div class="jsub">${to?'':'<button id="jt">Về hôm nay</button>'}${sp?`<span>Ngày này đã chi ${fmt(sp)}</span>`:''}</div><div class="jmood" id="jmo">${MOODS.map(m=>`<button type="button" data-m="${m}" class="${m==mood?'on':''}">${ico(MI[m],26)}<span>${m}</span></button>`).join('')}</div><textarea id="jx" placeholder="Hôm nay của bạn thế nào?">${esc(txt)}</textarea><div class="jfoot"><span id="jst">${e?'Đã lưu':'Tự động lưu khi bạn viết'}</span><span id="jc">${txt.length} ký tự</span></div></div><div class="jlw"><div class="tools"><input id="jq" placeholder="Tìm trong nhật ký" value="${esc(JQ)}"></div><div class="card" id="jl">${jlist()}</div></div></div>`;
const st=t=>{const s=$('#jst');if(s)s.textContent=t};
const save=async()=>{clearTimeout(timer);if(!dirty)return;dirty=false;const x=txt.trim();if(!x&&!mood){st('Tự động lưu khi bạn viết');return}const cur=J.find(z=>z.id==day),now=Date.now();await run('journal',s=>s.put({id:day,date:day,text:x,mood,createdAt:cur?cur.createdAt:now,updatedAt:now}));J=await getAll('journal');st('Đã lưu');const l=$('#jl');if(l)l.innerHTML=jlist()};
const mark=()=>{dirty=true;st('Đang lưu…');clearTimeout(timer);timer=setTimeout(save,700)};
jFlush=save;
const tx=$('#jx'),fit=()=>{tx.style.height='auto';tx.style.height=Math.max(180,tx.scrollHeight)+'px'};fit();
tx.oninput=()=>{txt=tx.value;$('#jc').textContent=txt.length+' ký tự';fit();mark()};
document.querySelectorAll('#jmo [data-m]').forEach(b=>b.onclick=()=>{mood=mood==b.dataset.m?'':b.dataset.m;document.querySelectorAll('#jmo [data-m]').forEach(x=>x.classList.toggle('on',x.dataset.m==mood));mark()});
if($('#jt'))$('#jt').onclick=()=>{JD=td();render()};
$('#jdi').onchange=ev=>{if(ev.target.value){JD=ev.target.value;render()}};$('#jdi').onclick=ev=>{try{ev.target.showPicker()}catch(x){}};
$('#jq').oninput=ev=>{JQ=ev.target.value;$('#jl').innerHTML=jlist()}}
function cal(){if(CT=='j'){jr();return}const[y,m]=M.split('-').map(Number),first=(new Date(y,m-1,1).getDay()+6)%7,n=new Date(y,m,0).getDate(),l=inM(M),days=new Set(l.map(t=>t.date)),ex={};l.forEach(t=>{if(t.type=='expense')ex[t.date]=(ex[t.date]||0)+t.amount});
let g='T2 T3 T4 T5 T6 T7 CN'.split(' ').map(d=>`<b>${d}</b>`).join('')+'<span></span>'.repeat(first);
for(let d=1;d<=n;d++){const k=M+'-'+p2(d),c=days.has(k)&&S.daily>0?((ex[k]||0)>S.daily?'bad':'ok'):'';g+=`<button data-day="${k}" class="${days.has(k)?'dot':''} ${J.some(x=>x.id==k)?'jn':''} ${c} ${CALD==k?'sel':''} ${k==td()?'today':''}">${d}</button>`}
const dl=CALD?T.filter(t=>t.date==CALD):[];
app.innerHTML=`<h2>Lịch</h2>${ctabs()}${pn(mLabel(M))}<div class="card"><div class="cal">${g}</div><p style="color:var(--mut);font-size:13px;margin:10px 0 0">Chỉ tiêu: ${fmt(S.daily)}/ngày</p></div>${CALD?`<div class="card"><h3 style="margin-top:0">${dmy(CALD)}</h3>${dl.length?`<p>Đã chi <b>${fmt(ex[CALD]||0)}</b> / ${fmt(S.daily)}</p>${ex[CALD]?topLine(CALD):''}`+dl.map(txRow).join(''):'<p class="empty">Không có giao dịch trong ngày này.</p>'}${jBlock(CALD)}</div>`:''}`}
const PALC=['#F97316','#EAB308','#84CC16','#22A06B','#14B8A6','#06B6D4','#0EA5E9','#6366F1','#8B5CF6','#D946EF','#EC4899','#F43F5E','#EF4444','#78716C','#64748B','#111111'];
const catRow=c=>`<div class="cr"><button class="cic" data-pick="${c.id}" style="background:${c.color}22;color:${c.color}" aria-label="Đổi biểu tượng và màu">${ico(c.icon,22)}</button><input class="cn" type="text" value="${esc(c.name)}" data-cn="${c.id}" maxlength="30" placeholder="Tên danh mục" aria-label="Tên danh mục"><button class="cd" data-cd="${c.id}" aria-label="Xóa">${ico('trash',18)}</button></div>`;
const catEditor=()=>['expense','income'].map(t=>`<h3>${t=='income'?'Thu nhập':'Chi tiêu'}</h3>`+C.filter(c=>c.type==t).map(catRow).join('')+`<div class="btns"><button data-nc="${t}">+ Thêm danh mục ${t=='income'?'thu':'chi'}</button></div>`).join('');
function pickCat(id){const c=C.find(x=>x.id==id),ci=EM[c.icon]||c.icon,sv=()=>run('categories',s=>s.put(c)).then(()=>pickCat(id));
dlg.innerHTML=`<h2 style="display:flex;align-items:center;gap:12px"><span class="cic" style="background:${c.color}22;color:${c.color}">${ico(c.icon,22)}</span>${esc(c.name)}</h2><label>Biểu tượng</label><div class="pg" id="pi">${CI.map(k=>`<button type="button" data-k="${k}" class="${ci==k?'on':''}" style="${ci==k?`background:${c.color}22;color:${c.color}`:''}">${ico(k,22)}</button>`).join('')}</div><label>Màu sắc</label><div class="pg" id="pc">${PALC.map(h=>`<button type="button" data-h="${h}" class="sw ${h.toLowerCase()==c.color.toLowerCase()?'on':''}" style="background:${h}" aria-label="${h}"></button>`).join('')}<input type="color" id="cu" value="${c.color}" aria-label="Màu tùy chọn"></div><div class="btns"><button type="button" class="pri" id="cx">Xong</button></div>`;
if(!dlg.open)dlg.showModal();
document.querySelectorAll('#pi [data-k]').forEach(b=>b.onclick=()=>{c.icon=b.dataset.k;sv()});
document.querySelectorAll('#pc [data-h]').forEach(b=>b.onclick=()=>{c.color=b.dataset.h;sv()});
$('#cu').onchange=e=>{c.color=e.target.value;sv()};$('#cx').onclick=()=>dlg.close();dlg.onclose=()=>{dlg.onclose=null;if(V=='set')set()}}
function set(){app.innerHTML=`<h2>Cài đặt</h2><div class="card" id="sync"></div><div class="card"><label>Chỉ tiêu chi mỗi ngày (₫)</label><input id="bd" type="number" min="0" step="10000" value="${S.daily}"></div><div class="card"><label>Giao diện</label><select id="th"><option value="system">Theo hệ thống</option><option value="light">Sáng</option><option value="dark">Tối</option></select></div><div class="card"><h3 style="margin-top:0">Danh mục</h3><p style="color:var(--mut);font-size:13px;margin:0 0 4px">Chạm vào tên để đổi tên. Chạm vào biểu tượng để đổi icon và màu.</p>${catEditor()}</div><div class="card"><h3 style="margin-top:0">Dữ liệu</h3><div class="btns"><button data-x="json">Xuất JSON</button><button data-x="csv">Xuất CSV</button></div><div class="btns"><button id="imp">Nhập JSON</button><input id="file" type="file" accept=".json" hidden></div><div class="btns"><button data-demo>Tạo dữ liệu demo</button><button data-cdemo>Xóa dữ liệu demo</button></div><p style="color:var(--mut);font-size:13px">Dữ liệu chỉ lưu trong trình duyệt của bạn (IndexedDB), không gửi đi đâu.</p></div>`;
window.mfSyncUI&&mfSyncUI();$('#th').value=S.theme;$('#bd').onchange=e=>{S.daily=Math.max(0,+e.target.value||0);run('settings',x=>x.put({key:'daily',value:S.daily}))};$('#th').onchange=e=>{S.theme=e.target.value;saveS();applyTheme()};
$('#imp').onclick=()=>$('#file').click();$('#file').onchange=importJ;
const ed=(a,k)=>document.querySelectorAll('['+a+']').forEach(e=>e.onchange=async()=>{const c=C.find(x=>x.id==e.getAttribute(a));if(k=='name'&&!e.value.trim()){e.value=c.name;return}c[k]=e.value.trim()||c[k];await run('categories',s=>s.put(c))});ed('data-ci','icon');ed('data-cn','name');ed('data-cc','color')}
/* ---- actions ---- */
function form(id){const t=T.find(x=>x.id==id)||{type:'expense',amount:'',categoryId:'',date:td(),note:''};let ty=t.type,items=(t.items||[]).map(x=>({...x}));
const opts=y=>C.filter(c=>c.type==y).map(c=>`<option value="${c.id}" ${t.categoryId==c.id?'selected':''}>${esc(c.name)}</option>`).join('');
dlg.innerHTML=`<h2>${id?'Sửa':'Thêm'} giao dịch</h2><div class="seg" id="ty"><button type="button" data-t="expense" class="${ty=='expense'?'on':''}">Chi tiêu</button><button type="button" data-t="income" class="${ty=='income'?'on':''}">Thu nhập</button></div><label>Số tiền (₫)</label><input id="fa2" inputmode="numeric" autocomplete="off" placeholder="150.000" value="${dv(t.amount)}" ${t.amount%1000?'data-ex="1"':''}><label>Danh mục</label><select id="fc2">${opts(ty)}</select><div id="mk"></div><label>Ngày</label><div class="ce"><button type="button" id="td" class="tdb">Hôm nay</button><label class="tdb dp" id="dp"><span id="dl">Chọn ngày</span><input id="fd" type="date" value="${t.date}"></label></div><label>Ghi chú</label><input id="fn" value="${esc(t.note)}" placeholder="Ăn trưa"><p id="er" class="exp"></p><div class="btns"><button type="button" id="cx">Hủy</button><button type="button" class="pri" id="sv">Lưu</button></div>`;
const fi=e=>{const el=e.target;let v=el.value;if(el.dataset.ex){const d=v.replace(/\D/g,'');if(d){el.value=nf(+d);return +d}delete el.dataset.ex;el.value='';return 0}
if(v.endsWith('.000'))v=v.slice(0,-4);const d=v.replace(/\D/g,'').replace(/^0+/,'');el.value=d?nf(+d)+'.000':'';const p=d?el.value.length-4:0;el.setSelectionRange(p,p);return d?+d*1000:0};
const isM=()=>ty=='expense'&&$('#fc2').value=='c17';
const tot=()=>{const s=items.reduce((a,x)=>a+(x.amount||0),0);const f=$('#fa2');if(s){if(s%1000)f.dataset.ex=1;else delete f.dataset.ex;f.value=dv(s)}};
const mkUI=()=>{const b=$('#mk');if(!isM()){b.innerHTML='';return}
b.innerHTML='<label>Các khoản đã mua (tùy chọn)</label>'+items.map((x,i)=>`<div class="ce"><input type="text" placeholder="Món (cà chua...)" value="${esc(x.name)}" data-in="${i}"><input class="mo" inputmode="numeric" placeholder="Tiền" value="${dv(x.amount)}" ${x.amount%1000?'data-ex="1"':''} data-ia="${i}"><button type="button" data-ix="${i}" aria-label="Xóa">${ico('trash',18)}</button></div>`).join('')+'<button type="button" id="ai" class="pri" style="margin:0 0 4px">+ Thêm món</button>';
b.querySelectorAll('[data-in]').forEach(e=>e.oninput=()=>items[e.dataset.in].name=e.value);
b.querySelectorAll('[data-ia]').forEach(e=>e.oninput=ev=>{items[e.dataset.ia].amount=fi(ev);tot()});
b.querySelectorAll('[data-ia]').forEach(e=>{e.onclick=cl;e.onfocus=cl});b.querySelectorAll('[data-ix]').forEach(e=>e.onclick=()=>{items.splice(e.dataset.ix,1);mkUI();tot()});
$('#ai').onclick=()=>{items.push({name:'',amount:0});mkUI();b.querySelector('[data-in="'+(items.length-1)+'"]').focus()}};
dlg.showModal();$('#fa2').focus();mkUI();$('#fa2').oninput=fi;$('#fa2').onclick=cl;$('#fa2').onfocus=cl;$('#fc2').onchange=mkUI;
document.querySelectorAll('#ty button').forEach(b=>b.onclick=()=>{ty=b.dataset.t;document.querySelectorAll('#ty button').forEach(x=>x.classList.toggle('on',x==b));$('#fc2').innerHTML=opts(ty);mkUI()});
$('#cx').onclick=()=>dlg.close();
const syncTd=()=>{const v=$('#fd').value,to=v==td();$('#td').classList.toggle('on',to);$('#dp').classList.toggle('on',!to);$('#dl').textContent=to||!v?'Chọn ngày':dmy(v)};$('#td').onclick=()=>{$('#fd').value=td();syncTd()};$('#fd').onchange=syncTd;$('#fd').onclick=()=>{try{$('#fd').showPicker()}catch(e){}};syncTd();
$('#sv').onclick=async()=>{const list=isM()?items.filter(x=>x.name.trim()||x.amount).map(x=>({name:x.name.trim(),amount:x.amount||0})):[];let a=val($('#fa2'));if(list.some(x=>x.amount))a=list.reduce((s,x)=>s+x.amount,0);const d=$('#fd').value;if(!a){$('#er').textContent='Nhập số tiền lớn hơn 0.';return}if(!d||!$('#fc2').value){$('#er').textContent='Chọn danh mục và ngày.';return}
const now=Date.now(),n={...t,id:t.id||uid(),type:ty,amount:a,categoryId:$('#fc2').value,date:d,note:$('#fn').value.trim(),createdAt:t.createdAt||now,updatedAt:now};delete n.items;if(list.length)n.items=list;await run('transactions',x=>x.put(n));T=await getAll('transactions');dlg.close();render()}}
const dl=(name,txt,mime)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:mime}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function exportX(k){if(k=='json')return dl('moneyflow-backup-'+td()+'.json',JSON.stringify({app:'moneyflow',version:1,transactions:T,categories:C,journal:J,settings:S},null,1),'application/json');
const q=v=>'"'+String(v).replace(/"/g,'""')+'"';dl('moneyflow-'+td()+'.csv','\ufeffNgày,Loại,Danh mục,Số tiền,Ghi chú\n'+[...T].sort((a,b)=>b.date.localeCompare(a.date)).map(t=>[dmy(t.date),t.type=='income'?'Thu nhập':'Chi tiêu',q(cat(t.categoryId).name),t.amount,q(t.note+(t.items&&t.items.length?' ['+t.items.map(x=>x.name+': '+x.amount).join('; ')+']':''))].join(',')).join('\n'),'text/csv')}
async function importJ(e){const f=e.target.files[0];e.target.value='';if(!f)return;let d;
try{d=JSON.parse(await f.text());if(d.app!='moneyflow'||!Array.isArray(d.transactions)||!Array.isArray(d.categories))throw 0;const ids=new Set(d.categories.map(c=>c.id));if(d.categories.some(c=>!c.id||!c.name||!['income','expense'].includes(c.type)))throw 0;
if(d.transactions.some(t=>!t.id||!['income','expense'].includes(t.type)||!(t.amount>0)||!/^\d{4}-\d{2}-\d{2}$/.test(t.date)||!ids.has(t.categoryId)))throw 0;if((d.journal||[]).some(x=>!x.id||!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||typeof x.text!='string'))throw 0}
catch{alert('File không hợp lệ. Dữ liệu hiện tại được giữ nguyên.');return}
if(!confirm('Thay toàn bộ dữ liệu hiện tại bằng file này?'))return;
await run(['transactions','categories','journal'],(a,b,j)=>{a.clear();b.clear();j.clear();d.transactions.forEach(x=>a.put(x));d.categories.forEach(x=>b.put(x));(d.journal||[]).forEach(x=>j.put(x))});T=await getAll('transactions');C=await getAll('categories');J=await getAll('journal');alert('Đã nhập dữ liệu.');render()}
async function demo(){const y=+td().slice(0,4),ex=C.filter(c=>c.type=='expense'),inc=C.find(c=>c.name=='Lương'),n=[];
for(let m=Math.max(1,+M.slice(5)-3);m<=+M.slice(5);m++){const k=y+'-'+p2(m);n.push({type:'income',amount:11e6+m*2e5,categoryId:inc.id,date:k+'-01',note:'Lương tháng '+m});
ex.slice(0,6).forEach((c,i)=>n.push({type:'expense',amount:(80+((m*37+i*53)%300))*1e4/2,categoryId:c.id,date:k+'-'+p2(2+i*4),note:'Demo '+c.name}))}
const now=Date.now();await run('transactions',s=>n.forEach((x,i)=>s.put({...x,id:'demo'+uid()+i,demo:true,createdAt:now+i,updatedAt:now})));T=await getAll('transactions');render()}
async function clearDemo(){await run('transactions',s=>T.filter(t=>t.demo).forEach(t=>s.delete(t.id)));T=await getAll('transactions');render()}
/* ---- router & events ---- */
function render(){jFlush=null;app.classList.remove('wide');charts.forEach(c=>c.destroy());charts=[];document.querySelectorAll('#nav [data-v]').forEach(b=>b.classList.toggle('on',b.dataset.v==V));({dash,tx:txs,rep,cal,set})[V]()}
const go=v=>{if(v=='cal'){M=td().slice(0,7);CALD=td()}V=v;render();scrollTo(0,0)};
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-cat],[data-jd]');if(!b)return;const d=b.dataset;if(jFlush)await jFlush();
if(d.v)go(d.v);else if(b.id=='fab'||b.id=='addBtn'||'add' in d)form();
else if(d.e)form(d.e);
else if(d.d){if(confirm('Xóa giao dịch này?')){await run('transactions',s=>s.delete(d.d));T=await getAll('transactions');render()}}
else if(d.p){const n=+d.p;if(V=='rep'&&RT=='y')Y+=n;else if(V=='rep'&&RT=='w')WK=addD(WK,7*n);else M=shift(M,n);CALD=null;render()}
else if(d.rt){RT=d.rt;render()}
else if(d.day){CALD=d.day;render()}
else if(d.cat){F=V=='rep'&&RT=='w'?{c:d.cat,d1:WK,d2:addD(WK,6),t:'expense'}:RT=='y'&&V=='rep'?{c:d.cat,y:Y,t:'expense'}:{c:d.cat,m:M,t:'expense'};go('tx')}
else if('clr' in d){F={};render()}
else if(d.x)exportX(d.x)
else if('demo' in d)demo();else if('cdemo' in d)clearDemo();
else if(d.pick)pickCat(d.pick);else if(d.jn){JD=addD(JD,+d.jn);render()}else if(d.ct){CT=d.ct;render()}else if('jw' in d){JD=CALD||td();CT='j';render()}else if(d.jd){JD=d.jd;render();scrollTo(0,0)}else if(d.jx){if(confirm('Xóa nhật ký này?')){await run('journal',s=>s.delete(d.jx));J=await getAll('journal');render()}}
else if(d.nc){const n={id:'c'+uid(),type:d.nc,icon:'star',name:'Danh mục mới',color:'#0f766e'};await run('categories',s=>s.put(n));C=await getAll('categories');render()}
else if(d.cd){if(confirm('Xóa danh mục này? Giao dịch cũ sẽ hiển thị là "Đã xóa".')){await run('categories',s=>s.delete(d.cd));C=await getAll('categories');render()}}});
(async()=>{db=await openDB();T=await getAll('transactions');C=await getAll('categories');J=await getAll('journal');
if(!localStorage.mf_v3){await run('categories',s=>DC.forEach(d=>{const e=C.find(x=>x.id==d.id);s.put(e?{...e,icon:d.icon,color:d.color}:d)}));localStorage.mf_v3=1;C=await getAll('categories')}
if(!localStorage.mf_v4){await run('categories',s=>DC.forEach(d=>{const e=C.find(x=>x.id==d.id);if(e&&/^#([0-9a-f]{2})\1\1$/i.test(e.color))s.put({...e,color:d.color})}));localStorage.mf_v4=1;C=await getAll('categories')}
const s=await getAll('settings');const t=s.find(x=>x.key=='theme');if(t)S.theme=t.value;const dv=s.find(x=>x.key=='daily');if(dv)S.daily=dv.value;document.querySelectorAll('[data-ic]').forEach(b=>b.insertAdjacentHTML('afterbegin',ico(b.dataset.ic,22)));applyTheme();render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})})();

window.mfDB=()=>db;window.mfRefresh=async()=>{T=await getAll('transactions');C=await getAll('categories');J=await getAll('journal');if(!dlg.open&&!/TEXTAREA|INPUT/.test(document.activeElement.tagName))render()};
